### ISSUE TITLE
lang is not supported ru

### ISSUE THREAD

**Issue by musichen** [alibaba/react-intl-universal#51]
I've used react-intl-universal to fetch multiple languages:  de, en, fr, ja, ru, zh

When switching the lang, performing the re-init   intl.init()   into ru-RU
i've got a warning that RU is not supported, locale get loaded and works just fine. 
I wonder why the warning. 

Here is the log:

<img width="911" alt="screen shot 2018-04-02 at 19 16 20" src="https://user-images.githubusercontent.com/7377421/38206413-a07a269e-36aa-11e8-841a-758b5b9918ae.png">

here is locales structure: 

<img width="256" alt="screen shot 2018-04-02 at 19 20 04" src="https://user-images.githubusercontent.com/7377421/38206494-e73c85f4-36aa-11e8-967e-63966046645e.png">

here is  ru-RU.json 
<img width="894" alt="screen shot 2018-04-02 at 19 21 39" src="https://user-images.githubusercontent.com/7377421/38206547-1c5dfc36-36ab-11e8-8294-081bc6d83576.png">

**Comment by cwtuan** [comment]
fixed in v1.9.2

**Comment by musichen** [comment]
thanks for prompt actions on fixing this issue.

**Comment by musichen** [comment]
on my side still not fixed.  
I have updated react-intl-universal

![image](https://user-images.githubusercontent.com/7377421/38471040-f6f34d78-3b6b-11e8-81de-1cf716e12e41.png)

I still receive the warning of unsupported RU lang 

![image](https://user-images.githubusercontent.com/7377421/38471047-0bea6ffe-3b6c-11e8-95b3-cb801b16225b.png)

@cwtuan could you please have a look at it again?

Thanks in advance!

**Comment by cwtuan** [comment]
@musichen 
It works on my side.
What's your `currentLocale`? Could you log it?

**Comment by cwtuan** [comment]
BTW, could you please provide your `ru-RU.json` to me?

**Comment by musichen** [comment]
currentLocale: 'en-US'

my   ru-RU.json:

```
{
  "SIMPLE": "Простое предложение",
  "HELLO": "Привет, {name}. Добро пожаловать на {where}!",
  "TIP": "Это хтмл тип перевода <span style='color:red'>HTML</span>",
  "TIP_VAR": "Это перевод с ХТМЛ а также с перменной <span style='color:red'>{message}</span>",
  "SALE_START": "Распродажа начинается {start, date}",
  "SALE_END": "Распродажа заканчивается {end, date, long}",
  "COUPON": "Купон истекает {expires, time, medium}",
  "SALE_PRICE": "Цена {price, number, USD}",
  "PHOTO": "У вас {photoNum, plural, =0 {нет фотографий.} =1 {одна фотография.} other {# фотографий.}}",
  "MESSAGE_NOT_IN_COMPONENT": "react-intl-universal не может интернационализировать в React.Component, так как перевод отсуствует для компонента"
}

```

**Comment by kspacja** [comment]
Hi, 

I didn't wanted to create new issue, cause my is the same, but app, what I'm writing, has to support polish language.

Thanks in advanced

**Comment by cwtuan** [comment]
@kspacja Try version 1.11.2.

**Comment by maksimovicdanijel** [comment]
I also have an issue that lang nl is not supported, working with 1.11.2 version.

**Comment by cwtuan** [comment]
@maksimovicdanijel Try v1.11.3.

**Comment by rashmendis** [comment]
lang "sv" is not supported. v.1.11.1

**Comment by cwtuan** [comment]
@rashmendis 
Try v1.11.4.

**Comment by h4mit** [comment]
lang "fa" is not supported. my version : ^1.12.1

**Comment by cwtuan** [comment]
@h4mit 
"fa" is supported in v1.12.2. 
However, you can also customize `commonLocaleDataUrls` to support more languages since [v1.12.0](https://github.com/alibaba/react-intl-universal/releases/tag/1.12.0).
